version: '2'
services:
  web:
    restart: always
    build: .
    container_name: cherrydoor_web-data
    ports:
     - "7000:7000"
    environment:
     - NODE_ENV=cherrydoor-local
     - DB_1_PORT_27017_TCP_ADDR=db
    depends_on:
     - db
    volumes_from:
     - web-data
  web-data:
    build: .
    entrypoint: /bin/true
    volumes:
     - ./:/opt/cherrydoor
     - /opt/cherrydoor/node_modules
     - /opt/cherrydoor/public
  db:
    image: mongo:3.4
    restart: always
    ports:
     - "27017:27017"
    volumes_from:
      - db-data
  db-data:
    image: mongo:3.4
    volumes:
      - /data/db
      - /var/lib/mongodb
      - /var/log/mongodb
    entrypoint: /bin/true
